development:
  password: ${SHOPIFY_API_PASSWORD}
  theme_id: ${DEVELOPMENT_THEME_ID}
  store: patricksherwin.myshopify.com
  ignore_files:
    - "*.gif"
    - config/settings_data.json

staging:
  password: ${SHOPIFY_API_PASSWORD}
  theme_id: ${STAGING_THEME_ID}
  store: patricksherwin.myshopify.com

production:
  password: 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
  theme_id: ${PRODUCTION_THEME_ID}
  store: patricksherwin.myshopify.com
  timeout: 60s
  readonly: true
