development:
  password: ${SHOPIFY_API_PASSWORD}
  theme_id: ${DEVELOPMENT_THEME_ID}
  store: patricksherwin.myshopify.com
  ignore_files:
    - "*.gif"
  
  

staging:
  password: ${SHOPIFY_API_PASSWORD}
  theme_id: ${STAGING_THEME_ID}
  store: patricksherwin.myshopify.com

  
production:
  password: ${SHOPIFY_API_PASSWORD}
  theme_id: ${PRODUCTION_THEME_ID}
  store: patricksherwin.myshopify.com

  

